language: node_js
node_js: 6
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./application/node_modules"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/install_compose.sh ; fi
- cd application
before_script:
- npm run start:mongodb
script:
- sleep 15
- npm run lint
- npm run test
after_success:
- cd ..
- openssl aes-256-cbc -K $encrypted_09ff33532be1_key -iv $encrypted_09ff33532be1_iv -in deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- npm run coverall
- npm run stop:mongodb
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: piHOz05GT11tJwKhQpxj0lVd1kxKYmmCfZLfDcJHb5xpRxNHGkKnQJitT5aX8MRvC0sjxmn62/0w6XYVtL8P25ZAF8cBHa5tzQfNQsXDdq003k+FGgY+aDIPqbXemRy99NDamG/3yl2e6M/P8PiIqjN2KpIAwGEFv0okO1m1i8O5gV4wt/fwbxFSV+UCGnUY6e3TWUCcmbYAnfrSPvvL7c669DQj9WxLB576CNN71B5AFGTqMUibo28iTgOBfYPquEIgsdGzzJs7vjuFxHrjkA6lQ6P2GRH/AO7LcERQO/6SxF0ZDIJIFySgwdIZ2qkb1PVVt4IJDLvIGVySW33i2mifr+y5O6CFO7zFwCd4S9hxwSAQQ0R4ZXC6w1cMJ/gAZZXqxh6GQuYKnNxaLEd442Hx87C+XonmI9Md+pvQTrRrB+o4vbKyK2R/GawJ1Lzb1A9k3Gpd/bzgzbf8qgRsC7CrT2Rize9QdUcwTfJ6Ob2YcUb5tYV3A238bGpjMTMgkVxyAmCGUiiNAUCG1DofMHF0ZOT7LqE7eInVgghRJr21hQu7pksObaqKHVWfiTfuL+khVaBSPkeOjJjysMcxOLQlsEBiPVv+CnN6ofKq6KjgwNoE2oYXcYKI1dHqOY6nu8C9ZWmYDl65W+uewnH9bbVQA1N9y59HTfpp0pMjo+0=
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
  - DATABASE_PORT=27018
  - secure: QgUUwLUximaLY9QrDa46vAFKitMv4pj9d/1MVnOnAgDEce293vgdiQR94pCi/ngxYNX+HoG4Yas8qpro8H/zZp9HDmihursFyc4vHViM0nlWRSuozce9g3+wXvNt87NMXx/01mOqQHB6pYEO8+/TtKzS0DHvJh4YCJr+SSTRB9SvN/g2Ecfhtr5l43UuA+c//t7UxfrKdxB7MaQgfe30vr0o3QBJ08hD/dxgu3deu4UuZei88GnPYVDuynAsbZCX90bGon4nJVpjbcSn/f8pRfGallU1QShp/nTv7AAADpMesi5K2aTpsRh4vEXD77nOpvLnt/rwV7SgivyCrI5HUE34vTplLpbC7877g8NFKqB218c8Js2/P0/OkrjpvbNfAit4ACEJmbWuwaf2WyxSGgRtFUlgqCUGM4QUcvhOZh9Vm6hMDoQMib0e2T380IBPzAuDpxJjnYT85qw3lN1LltqjFHjqMF191cNtBxed8Vo4CWLexAXQ0MLzyDa5yP0rH+eu40yjPJv3aUgxz0LW7f4wkgwTGdSujBURhYXbW3w4rv3c2naHmPzy6wc5dkWFllMF45c9rfqcbuPD+BGYbyE8KK2BdhMUCJzPIClOZ/m3T/TLp6FezjcTMUK0+FAr2J/f2zvai68ay4uFgn9eix+S1GrHIxwNeUlMqrrg0PM=
  - secure: b/vt2FeOkAjWURXFmVKL5dvZHEPYx0aMG12FR71WQ8wtpFMiZpS2OLw8TGjjP5PLrjsV14wSEtd6LlZ01s2bK7jNGsK6yBykfa0OHXyneiZsYgqa3m9ITfCO4UB/9WCQMB5QpJHCTBjjibVO1KCwfpQtZw7Wgh5tmI/A5Xmf0EMhNKndXTxoxstmcDnBgdRQIxbDgtKRHFngezQLWFUThaKSh19SEXjaJ0+/QC/ehRjUrMEYDV2IaiA6F2GV7LFtHT5c6PYF8RYBZpSO035prIpt6NieW29MhyYv/ytTNQPMSep7lArGM/y/hAlo1I1W7YBx3g4VaC1J8r7SiwZPY/Zhyks/JbQhk9334xFQYhqCEhyiTdpMeRj6bj0OrKjE1m0edG2M9XY04xLadgmARswQDwIrx3d7Ab1Ns6Rvn5HyVq+gleQPFhWr6g3lvQahK56nHgo5EsIwGxUA8Q4Kl5AcXyIFe7+00u/eOoJ7o6bLIGU/YwG50+qthFebdTE9Pjk98oPBsZNLbMTjI0pjz+e8V0OyWWSMJ+wlewnRTKCDoCwJpqcjdYJdaxtxs0Jljc4LDn3IlvfADL6vOX+2TNQz8fEBngo1qHNr42Z1t6KQ0ldT1YCGhr0jnZRH7DrUytvd9UeqNLFUln4CDvFKTaTibbX2YVdbHpUaRcCMnHk=
  - secure: SYlAzm3Ev14OOpGOkxqMT85NNVof+13TkNz443JhlmAh3O7YOwjNiLvtEK/UGDXsvctKLkvfMixqby/WQVOl4MSMYfcNs7U8sWqEsiYMPHeWuCsom1Uj7PUsHSKNvyFW/3U+XITVtxzgXRoHvqMNsMWwID0P+2xHAJo3SXofZp6/8CvYmBppOmC92ja4t2O2KehT42I3e3Ur/NKzNQV7ha6SfxT7MUJrrj9mv6cXsJRrFgvRNrdslMDXlbQrgXzrv2Fp7VvL//xmT+1CxOMAG1Nx20XCayDXKTnChIEil6vOE+ab4216dJCUG3Ag8fYmQHXAwhm2xh0UoF8WwwvGHrEXOSIBaU1eOccUrCBUgZNLYh5wb/EvOmLvWbdIMd/sP4GaPjD7JT4aNSgRa2qlR1S1OwHjVPwaJyAtEY9dS7pFwTQBaLx50kWI2u0dT+8IsP2ZL6nq/mIeSfPQU4fl4iqvO3wephKbc9irDZFSYqX9vAFQ3TWTMkIRnrQOVDsLTvI2o+BfPFl1yLLqkM99y+gsDTFNx9CrulKw1cku7rCpu3TH9x9o/CojnDzNyYMh2JEiicFiOCTxPj8xtgmPHck/J2hkpVmO2t05jx3XDc8ZK9zwEHdJl19Vbattgy0c8GIgb2mXc38sEdKU29Yqkx0Ju4ia8CAvhPbKhwm0Ug8=
  - secure: 2uj4vkl0xEsIVQPsh5KLEQcApJJ9Tjt4cyev0jkbD2+Ix+trizhmIMqSSvyYDZbHA6KOIOqrEnQJL5QbVDKjvjpVRfjhMnyM2NJT/BXFLlou66zui/nXgn0YxC7dDkAiQNq62cPutTv0i4oeIt/shLXG7ig+8fRrrs+CHSA3c95dM9cJmQVBc0HpJOLWttk6W8kcP6kn0RhXsESfnKPqXQ2mKtLahd+zUHbAHTVus4dl9dF+PVz+Sd4UfKYTNJgsk0jw7Zl5CtuJTxHyN+zhHRfSGmVJKfLdI0jAmQG2M9SlxsOpe9mUmMmOwYFBZw3LC8XiRS+f0D4JsBIF4nBCUSr5v7WIVLjqAuDALN8yjcEZkCY4ZC7LY0t+FnnTMBlI86f6rxh7KObLetLkgDIyL00xmoCmkiYgd9uYIHggHqdlwe4wgepMtm4O+8XEUD9ZfnHao/6Jb4bTzzuPecE8TdDgm2PUCM2oGI/ortaLieyMyexPM1sMJdpoaTPjASCuHcOeMAyrL4TK4GJTgbo8C5HF9TViZY9wIbx5kL/d3d3z6Y3ddM7u/vLDy+hQP7BOCXRjqwg+BgnYziyKe2ZmKcAJiu6dYjSvxnjpRW8Q7FBVXXVdZ8JUcFtQ6MKX9edY8YvXAT7H36rZiZy8xr0/Q5C0Jel7EJlX2o0/J8Lzpx8=
